### ISSUE TITLE
用注释的办法也不行了

### ISSUE THREAD

**Issue by wangzhiyong2019** [ddong1031/openwrt_cf#1]
![2021-09-06_193306](https://user-images.githubusercontent.com/52755729/132211506-4ee002b0-d883-4e39-8e3f-5c1b50739654.png)
dns解析出错

**Comment by ddong1031** [comment]
> ![2021-09-06_193306](https://user-images.githubusercontent.com/52755729/132211506-4ee002b0-d883-4e39-8e3f-5c1b50739654.png)
> dns解析出错

我刚改了下，你可以先删除原来的脚本 然后重新下试试  缓存名字同步远程APP名字，现在版本20210903，微信推送会出现版本号
