### ISSUE TITLE
大佬，测速地址失效了，如何自己制作测速地址？

### ISSUE THREAD

**Issue by hexsen929** [ddong1031/openwrt_cf#10]
我试着替换脚本里的测速地址，但是不起作用。。
想请问下 curl --resolve $domain:443:$1 https://$domain/$file -o /dev/null --connect-timeout 5 --max-time 10 > log.txt 2>&1
这个log.txt里面有什么内容呢，我想自己搭建一个测速地址给大家用

**Comment by hexsen929** [comment]
已搞定api

**Comment by histion** [comment]
怎么弄得，求教
