### ISSUE TITLE
建议同步更新最新版本

### ISSUE THREAD

**Issue by badafans** [ddong1031/openwrt_cf#2]
我看了你这里修改的数据，你所有的数据提交都是无效的。导致服务器无法给你提供IP学习功能。仅仅只提供地址列表下发

**Comment by ddong1031** [comment]
> 我看了你这里修改的数据，你所有的数据提交都是无效的。导致服务器无法给你提供IP学习功能。仅仅只提供地址列表下发

我刚微信正常收到更新的消息，版本号20210903，你可以先删除原来的脚本，缓存文件是通过远程app版本命名的

**Comment by badafans** [comment]
> > 我看了你这里修改的数据，你所有的数据提交都是无效的。导致服务器无法给你提供IP学习功能。仅仅只提供地址列表下发
> 
> 我刚微信正常收到更新的消息，版本号20210903，你可以先删除原来的脚本，缓存文件是通过远程app版本命名的

我意思是让你在20210903版本上更改，旧版本就不要用了

**Comment by badafans** [comment]
https://speed.cloudflare.com/__down  这个旧版的接口，调用频率多了会被workers限制，建议在0903版本的基础上重新修改整个脚本
