### ISSUE TITLE
昨天开始就不能用了

### ISSUE THREAD

**Issue by pingshu** [ddong1031/openwrt_cf#3]
昨天开始就不能用了

**Comment by pingshu** [comment]
今天可以了，源文件作者恢复更新了

**Comment by pingshu** [comment]
![2E5B75CB-BDED-4E2D-8280-DC666B9AF2A8](https://user-images.githubusercontent.com/22138807/147429870-9c483944-5ce3-4188-bfa8-ff926dcebfaa.jpeg)
又不能用了

**Comment by badafans** [comment]
> ![2E5B75CB-BDED-4E2D-8280-DC666B9AF2A8](https://user-images.githubusercontent.com/22138807/147429870-9c483944-5ce3-4188-bfa8-ff926dcebfaa.jpeg) 又不能用了

这个版本已经完全停止服务了

**Comment by ddong1031** [comment]
> > ![2E5B75CB-BDED-4E2D-8280-DC666B9AF2A8](https://user-images.githubusercontent.com/22138807/147429870-9c483944-5ce3-4188-bfa8-ff926dcebfaa.jpeg) 又不能用了
> 
> 这个版本已经完全停止服务了

跟随大佬脚步同步更新

**Comment by ddong1031** [comment]
> ![2E5B75CB-BDED-4E2D-8280-DC666B9AF2A8](https://user-images.githubusercontent.com/22138807/147429870-9c483944-5ce3-4188-bfa8-ff926dcebfaa.jpeg) 又不能用了

已更新

**Comment by pingshu** [comment]
可以了，谢谢
